# version: '3'

services:
  api1:
    build: .
    container_name: api1
    networks:
      - backend

  api2:
    build: .
    container_name: api2
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
