version: '3'

services:
  api1:
    build: ./go_api
    container_name: api1
    networks:
      - backend

  api2:
    build: ./go_api
    container_name: api2
    networks:
      - backend

  python_api1:
    build: ./python_api
    container_name: python_api1
    networks:
      - backend

  python_api2:
    build: ./python_api
    container_name: python_api2
    networks:
      - backend
  
  python_gunicorn_api1:
    build: ./python_gunicorn_api
    container_name: python_gunicorn_api1
    networks:
      - backend

  python_gunicorn_api2:
    build: ./python_gunicorn_api
    container_name: python_gunicorn_api2
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "8090:8090"
      - "8100:8100"
    networks:
      - backend

networks:
  backend:
