version: '3.9'

services:

  db_pg:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    shm_size: 128mb
    container_name: db_pg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend

  api1:
    build: ./go_api
    container_name: api1
    networks:
      - backend

  api2:
    build: ./go_api
    container_name: api2
    networks:
      - backend

  api_chi1:
    build: ./go_api_chi
    container_name: api_chi1
    networks:
      - backend

  api_chi2:
    build: ./go_api_chi
    container_name: api_chi2
    networks:
      - backend

  go_gin1:
    build: ./go_api_gin
    container_name: go_gin1
    depends_on:
      db_pg:
        condition: service_healthy
    environment:
      DB_URL: user=postgres password=password host=db_pg port=5432 dbname=postgres
    networks:
      - backend

  go_gin2:
    build: ./go_api_gin
    container_name: go_gin2
    depends_on:
      db_pg:
        condition: service_healthy
    environment:
      DB_URL: user=postgres password=password host=db_pg port=5432 dbname=postgres
    networks:
      - backend

  python_api1:
    build: ./python_api
    container_name: python_api1
    networks:
      - backend

  python_api2:
    build: ./python_api
    container_name: python_api2
    networks:
      - backend
  
  python_gunicorn_api1:
    build: ./python_gunicorn_api
    container_name: python_gunicorn_api1
    networks:
      - backend

  python_gunicorn_api2:
    build: ./python_gunicorn_api
    container_name: python_gunicorn_api2
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "8090:8090"
      - "8100:8100"
      - "8110:8110"
    networks:
      - backend

networks:
  backend:
    driver: bridge
