services:
  db_pg:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_pg-data:/var/lib/postgresql/data
    shm_size: 128mb
    container_name: db_pg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - backend

  go_api:
    build: ./go_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend

  go_api_chi:
    build: ./go_api_chi
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend

  go_gin:
    build: ./go_api_gin
    depends_on:
      db_pg:
        condition: service_healthy
    environment:
      DB_URL: user=postgres password=password host=db_pg port=5432 dbname=postgres
      SECRET: secret-jwt
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend

  python_api:
    build: ./python_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend

  python_gunicorn_api:
    build: ./python_gunicorn_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend

  flask:
    build: ./python_flask
    depends_on:
      db_pg:
        condition: service_healthy
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend

  nginx:
    image: nginx:alpine
    depends_on:
      - go_gin
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
      - "8010:8010"
      - "8020:8020"
      - "9000:9000"
      - "9010:9010"
      - "9020:9020"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend

networks:
  backend:
    driver: overlay

volumes:
  db_pg-data:
