version: '3.8'

services:
  db_pg:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_pg-data:/var/lib/postgresql/data
    shm_size: 128mb
    container_name: db_pg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - backend

  go_api:
    image: go_api
    build: 
      context: ./go_api
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    restart: always
    networks:
      - backend

  go_api_chi:
    image: go_api_chi
    build: 
      context: ./go_api_chi
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    restart: always
    networks:
      - backend

  go_gin:
    image: go_gin
    build: 
      context: ./go_api_gin
      dockerfile: Dockerfile
    depends_on:
      - db_pg
        # condition: service_healthy
    environment:
      DB_URL: user=postgres password=password host=localhost port=5432 dbname=postgres
      SECRET: secret-jwt
    deploy:
      replicas: 2
    restart: always
    networks:
      - backend

  python_api:
    image: python_api
    build: 
      context: ./python_api
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    restart: always
    networks:
      - backend

  python_gunicorn_api:
    image: python_gunicorn_api
    build: 
      context: ./python_gunicorn_api
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    restart: always
    networks:
      - backend

  flask:    
    image: flask
    build: 
      context: ./python_flask
      dockerfile: Dockerfile
    depends_on:
      - db_pg
        # condition: service_healthy
    deploy:
      replicas: 2
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
      - "8010:8010"
      - "8020:8020"
      - "9000:9000"
      - "9010:9010"
      - "9020:9020"
    deploy:
      replicas: 1
    depends_on:
      - flask
      - go_gin
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: overlay

volumes:
  db_pg-data:
